services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex
    restart: unless-stopped
    networks:
      - horizon_network
    volumes:
      - /Volume1/public/config/plex:/config
      - /Volume1/public/config/plex/tvseries:/tv
      - /Volume1/public/config/plex/movies:/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/Rome}
      - VERSION=docker
      #- PLEX_CLAIM= #optional
    labels:
      - com.centurylinklabs.watchtower.enable=true
