include:
  - ./adguard/docker-compose.yml
  - ./homepage/docker-compose.yml
  - ./nginxpm/docker-compose.yml
  - ./dozzle/docker-compose.yml
  - ./immich/docker-compose.yml
  - ./uptime/docker-compose.yml

networks:
  homelab_network:
    driver: bridge
    external: true
