include:
  - ./adguard/docker-compose.yml
  - ./dozzle/docker-compose.yml
  - ./immich/docker-compose.yml
  - ./nginxpm/docker-compose.yml
  - ./homepage/docker-compose.yml

networks:

  default:
    driver: bridge
    external: true
    name: ${EXTERNAL_NETWORK_NAME:-homelab_network}

  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: eth1 # using ifconfig
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          ip_range: "${ADGUARD_IP_ADDRESS:-192.168.1.3}/32"
          gateway: "192.168.1.1"
