services:
  dokploy:
    image: dokploy/dokploy:latest
    container_name: dokploy
    restart: unless-stopped
    ports:
      - 3002:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dokploy-data:/app
    environment:
      - NODE_ENV=production
    privileged: true
    healthcheck:
      test: [CMD, wget, --no-verbose, --tries=1, --spider, http://localhost:3000/]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true

volumes:
  dokploy-data:
    driver: local
