include:
  - ../_shared/networks.yml
  - ./uptime/docker-compose.yml
  - ./myspeed/docker-compose.yml
  - ./dozzle/docker-compose.yml
  - ./tugtainer/docker-compose.yml



# DEPRECATED - ./wud/docker-compose.yml
