services:
  # Homepage - Dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: homepage
    restart: unless-stopped
    networks:
      - homelab_network
    ports:
      - "${HOMEPAGE_HTTP_PORT:-3005}:3000"
    volumes:
      - /Volume1/public/config/homepage:/app/config
      - /Volume1/public/config/homepage/.env:/app/.env
      - /var/run/docker.sock:/var/run/docker.sock:ro
