services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - /Volume1/public/config/homepage:/app/config
      - /Volume1/public/config/homepage/.env:/app/.env
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${HOMEPAGE_HTTP_PORT:-3000}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
