services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    networks:
      - default
      - dockervlan:
          ipv4_address: ${HOMEPAGE_IP_ADDRESS:-192.168.1.4}
    volumes:
      - ${HOMEPAGE_CONFIG_DIR:-./config}:/app/config
      - ${HOMEPAGE_ENV_FILE:-./config/.env}:/app/.env
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "${HOMEPAGE_HTTP_PORT:-3015}:3000/tcp"

    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  dockervlan:
    external: true
