services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    networks:
      - default
      - dockervlan
    volumes:
      - /Volume1/public/config/homepage:/app/config
      - /Volume1/public/config/homepage/.env:/app/.env
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3015:3000/tcp"

networks:
  default:
    driver: bridge
    external: true
    name: ${EXTERNAL_NETWORK_NAME:-homelab_network}

  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: eth1 # using ifconfig
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          ip_range: "${ADGUARD_IP_ADDRESS:-192.168.1.3}/32"
          gateway: "192.168.1.1"
