services:
  # Dozzle - Docker Log Viewer
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    hostname: dozzle
    restart: unless-stopped
    networks:
      - homelab_network
    ports:
      - "${DOZZLE_HTTP_PORT:-9999}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DOZZLE_LEVEL=info
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
