services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    environment:
      DOZZLE_LEVEL: info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${DOZZLE_HTTP_PORT:-9999}:8080

    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    driver: bridge
    external: true
    name: ${EXTERNAL_NETWORK_NAME:-homelab_network}
