#
# WARNING: To install Immich, follow our guide: https://immich.app/docs/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.

name: immich

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich_server
    restart: unless-stopped
    networks:
      - horizon_network
    ports:
      - ${IMMICH_HTTP_PORT:-2283}:2283
    volumes:
      - immich-uploads:/data
      - /Volume1/media:/media
      - /Volume1/public/config/immich:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - IMMICH_CONFIG_FILE=/config/config.json
      - DB_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgresql:5432/${DB_DATABASE_NAME}
    depends_on:
      - redis
    healthcheck:
      disable: false
    labels:
      - com.centurylinklabs.watchtower.enable=true

  immich-machine-learning:
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich_machine_learning
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    restart: unless-stopped
    networks:
      - horizon_network
    volumes:
      - immich-model-cache:/cache
    healthcheck:
      disable: false
    labels:
      - com.centurylinklabs.watchtower.enable=true

  redis:
    image: docker.io/valkey/valkey:8-bookworm@sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571
    container_name: immich_redis
    restart: unless-stopped
    networks:
      - horizon_network
    volumes:
      - immich-redis-data:/data
    healthcheck:
      test: redis-cli ping || exit 1

volumes:
  # Media uploads - most important data
  immich-uploads:
    name: immich_uploads

  # ML model cache - can be recreated but saves time
  immich-model-cache:
    name: immich_model_cache

  # Redis data - sessions and cache
  immich-redis-data:
    name: immich_redis_data
