services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    hostname: adguard
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      # Expose port 53 on TCP and UDP for DNS queries
      - "53:53/tcp"
      - "53:53/udp"

      # Expose port 67 on UDP for DHCP server
      - "67:67/udp"

      # Expose port 80 on TCP for HTTP web interface
      - "${ADGUARD_HTTP_PORT:-8090}:80/tcp"

      # Expose port 443 on TCP and UDP for HTTPS web interface
      - "${ADGUARD_HTTPS_PORT:-8443}:443/tcp"
      - "${ADGUARD_HTTPS_PORT:-8443}:443/udp"

      # Expose port 3000 on TCP for AdGuard Home's API
      - "${ADGUARD_SETUP_PORT:-3000}:3000/tcp"

    volumes:
      - adguard-work:/opt/adguardhome/work
      - adguard-conf:/opt/adguardhome/conf

    environment:
      - TZ=${TZ:-Europe/Rome}

    # Security options
    cap_add:
      - NET_BIND_SERVICE # Allow binding to ports < 1024

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  adguard-work:
    name: adguard_work
  adguard-conf:
    name: adguard_conf

