services:
  # AdGuard Home - DNS Ad Blocker
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    hostname: adguard
    restart: unless-stopped
    networks:
      homelab_network:
        ipv4_address: 192.168.1.3
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3000:3000/tcp" # Setup port
      - "${ADGUARD_HTTP_PORT:-8090}:80/tcp"
      - "${ADGUARD_HTTPS_PORT:-8443}:443/tcp"
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    environment:
      - TZ=${TZ:-Europe/Rome}
    cap_add:
      - NET_BIND_SERVICE
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  adguard_work:
    name: adguard_work
  adguard_conf:
    name: adguard_conf
