services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    hostname: adguard
    restart: unless-stopped
    networks:
      dockervlan:
        ipv4_address: "${ADGUARD_IP_ADDRESS:-192.168.1.3}" # Static IP address for this container
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    # ports:
    #   # Expose port 53 on TCP and UDP for DNS queries
    #   - "53:53/tcp"
    #   - "53:53/udp"

    #   # Expose port 67 on UDP for DHCP server
    #   - "67:67/udp"

    #   # Expose port 68 on UDP for DHCP client
    #   # - "68:68/udp"

    #   # Expose port 80 on TCP for HTTP web interface
    #   - "${ADGUARD_HTTP_PORT:-8090}:80/tcp"

    #   # Expose port 443 on TCP and UDP for HTTPS web interface
    #   - "${ADGUARD_HTTPS_PORT:-443}:443/tcp"
    #   - "${ADGUARD_HTTPS_PORT:-443}:443/udp"

    #   # Expose port 3000 on TCP for AdGuard Home's API
    #   - "${ADGUARD_SETUP_PORT:-3000}:3000/tcp"

    #   # Expose port 853 on TCP for DNS-over-TLS (DoT)
    #   - "853:853/tcp"

    #   # Expose port 784 on UDP for DNS-over-QUIC (DoQ)
    #   - "784:784/udp"

    #   # Expose port 853 on UDP for DNS-over-DTLS (DoT)
    #   - "853:853/udp"

    #   # Expose port 8853 on UDP for DNS-over-TLS (DoT)
    #   - "8853:8853/udp"

    #   # Expose port 5443 on TCP and UDP for DNSCrypt
    #   - "5443:5443/tcp"
    #   - "5443:5443/udp"

    volumes:
      - ./config/adguardhome/work:/opt/adguardhome/work
      - ./config/adguardhome/conf:/opt/adguardhome/conf

    environment:
      - TZ=${TZ:-Europe/Rome}

    # Security options
    cap_add:
      - NET_BIND_SERVICE # Allow binding to ports < 1024

    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

# Networks configuration
networks:
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: eth1 # using ifconfig
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          ip_range: "${ADGUARD_IP_ADDRESS:-192.168.1.3}/32"
          gateway: "192.168.1.1"
