services:
  # Nginx Proxy Manager - Reverse Proxy
  nginxpm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxpm
    hostname: nginxpm
    restart: unless-stopped
    networks:
      - homelab_network
    ports:
      - "${NPM_HTTP_PORT:-80}:80"
      - "${NPM_HTTPS_PORT:-443}:443"
      - "${NPM_ADMIN_PORT:-81}:81"
    volumes:
      - nginxpm_data:/data
      - nginxpm_letsencrypt:/etc/letsencrypt
    environment:
      - DISABLE_IPV6=${NPM_DISABLE_IPV6:-true}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  nginxpm_data:
    name: nginxpm_data
  nginxpm_letsencrypt:
    name: nginxpm_letsencrypt
