services:
  nginxpm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxpm
    hostname: nginxpm
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.1.4
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - nginxpm_data:/data
      - nginxpm_letsencrypt:/etc/letsencrypt
    ports:
      - ${NPM_HTTP_PORT:-8080}:80
      - ${NPM_HTTPS_PORT:-6443}:443
      - ${NPM_ADMIN_PORT:-81}:81
    environment:
      DISABLE_IPV6: ${DISABLE_IPV6:-true}

volumes:
  nginxpm_data:
  nginxpm_letsencrypt:
