services:
  nginxpm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxpm
    hostname: nginxpm
    restart: unless-stopped
    # networks:
    #   default:
    #     ipv4_address: 192.168.1.4
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      # Named volumes - persists independently
      - nginxpm_data:/data
      - nginxpm_letsencrypt:/etc/letsencrypt
    ports:
      - ${NPM_HTTP_PORT:-80}:80
      - ${NPM_HTTPS_PORT:-443}:443
      - ${NPM_ADMIN_PORT:-81}:81
      # '127.0.0.1:81:81' # Admin Web Port

    environment:
      DISABLE_IPV6: ${DISABLE_IPV6:-true}
      #####DB_SQLITE_FILE: "nginxpm_data/database.sqlite"

    healthcheck:
      test: [ "CMD", "curl", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  nginxpm_data:
  nginxpm_letsencrypt:
