services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    # networks:
    #   default:
    #     ipv4_address: 192.168.1.5
    environment:
      DOZZLE_LEVEL: info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${DOZZLE_HTTP_PORT:-9999}:8080
