services:
  backend:
    image: ghcr.io/clabnet/wendy-backend:latest
    container_name: wendy-backend
    restart: unless-stopped
    environment:
      - DISABLE_AUTH=false
    env_file:
      - .env
    volumes:
      - /Volume1/media/upload/wendy:/app/upload
    ports:
      - 5454:5050
    networks:
      - horizon_network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  frontend:
    image: ghcr.io/clabnet/wendy-frontend:latest
    container_name: wendy-frontend
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=http://host.docker.internal:5454
    env_file:
      - .env
    ports:
      - 3454:80
    depends_on:
      - backend
    networks:
      - horizon_network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
