services:
  # Homepage - Dashboard
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: homepage
    restart: unless-stopped
    networks:
      - horizon_network
    ports:
      - ${HOMEPAGE_HTTP_PORT:-3005}:3000
    volumes:
      - /Volume1/public/config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - /Volume1/public/config/homepage/.env
    healthcheck:
      test: [CMD, wget, --no-verbose, --tries=1, --spider, http://localhost:3000/]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - com.centurylinklabs.watchtower.enable=true
