# https://github.com/solarorange/ansible-homelab

---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
# icons found here https://github.com/walkxcode/dashboard-icons

# - Organizer:
#     - Calendar:
#         name: Calendar
#         href: "{{HOMEPAGE_VAR_CALENDAR_URL}}"
#         widget:
#           type: calendar
#           firstDayInWeek: monday # optional - defaults to monday
#           view: monthly # optional - possible values monthly, agenda
#           maxEvents: 10 # optional - defaults to 10
#           showTime: true # optional - show time for event happening today - defaults to false
#           timezone: Europe/Rome # optional and only when timezone is not detected properly (slightly slower performance) - force timezone for ical events (if it's the same - no change, if missing or different in ical - will be converted to this timezone)
#           integrations: # optional
#             - type: ical # Show calendar events from another service
#               name: Dangerzone Events
#               url: "{{HOMEPAGE_VAR_CALENDAR_ICAL}}" # URL with calendar events
#               color: blue # optional - defaults to pre-defined color for the service (zinc for ical)
#               params: # optional - additional params for the service
#                 showName: true # optional - show name before event title in event line - defaults to false

- Infrastructure:
    - Portainer:
        description: Container Management
        icon: portainer.svg
        href: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        container: portainer
        widget:
            type: portainer
            url: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
            env: 3
            key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"

    - AdGuard Home:
        description: DNS Ad Blocker
        icon: adguard-home.png
        href: "{{HOMEPAGE_VAR_ADGUARD_URL}}"
        container: adguard
        widget:
            type: adguard
            url: "{{HOMEPAGE_VAR_ADGUARD_URL}}"
            username: "{{HOMEPAGE_VAR_ADGUARD_USER}}"
            password: "{{HOMEPAGE_VAR_ADGUARD_PWD}}"

    - Nginx Proxy Manager:
        description: Reverse Proxy Manager
        icon: nginx-proxy-manager.png
        href: "{{HOMEPAGE_VAR_NPM_URL}}"
        widget:
            type: npm
            url: "{{HOMEPAGE_VAR_NPM_URL}}"
            username: "{{HOMEPAGE_VAR_NPM_EMAIL}}"
            password: "{{HOMEPAGE_VAR_NPM_PWD}}"

- Monitoring:
    - Uptime Kuma:
        description: System monitoring
        icon: uptime-kuma.svg
        href: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
        container: uptimekuma
        widget:
            type: uptimekuma
            url: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
            slug: homelab

    - Speed test:
        description: Network speed test
        icon: si-speedtest.svg
        href: "{{HOMEPAGE_VAR_MYSPEED_URL}}"
        widget:
            type: myspeed
            url: "{{HOMEPAGE_VAR_MYSPEED_URL}}"

    - Tugtainer:
        description: Docker image update monitor
        icon: docker.png
        href: "{{HOMEPAGE_VAR_TUGTAINER_URL}}"
        container: tugtainer
        widget:
            type: iframe
            url: "{{HOMEPAGE_VAR_TUGTAINER_URL}}"

- Multimedia:
    - Immich:
        description: Self-hosted photo library
        icon: immich.svg
        href: https://photo.clabnet.com
        container: immich_server
        widget:
            type: immich
            version: 2
            url: "{{HOMEPAGE_VAR_IMMICH_URL}}"
            key: "{{HOMEPAGE_VAR_IMMICH_API_KEY}}"
            fields: ["photos", "videos"]

    # - Jellyfin:
    #     description: Self-hosted media library
    #     icon: jellyfin.png
    #     href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
    #     container: jellyfin
    #     widget:
    #         type: jellyfin
    #         url: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
    #         key: "{{HOMEPAGE_VAR_JELLYFIN_API_KEY}}"
    #         enableBlocks: "true"

- Home Automation:
    - Home Assistant:
        description: home
        icon: home-assistant.svg
        href: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
        container: homeassistant
        widget:
            type: homeassistant
            url: "{{HOMEPAGE_VAR_HOME_ASSISTANT_URL}}"
            key: "{{HOMEPAGE_VAR_HOME_ASSISTANT_API_KEY}}"

- Other:
    - Dozzle:
        description: Docker Logs
        icon: dozzle.png
        href: "{{HOMEPAGE_VAR_DOZZLE_URL}}"
