services:
  # Homeassistant Core
  homeassistant:
    image: home-assistant/home-assistant:latest
    container_name: homeassistant
    hostname: homeassistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - /Volume1/public/config/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=${TZ:-Europe/Rome}
    privileged: true
    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
    healthcheck:
      test: [CMD, curl, -f, http://localhost:8123/api/api]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
